CREATE TABLE TB_TODO(
	TODO_NO NUMBER CONSTRAINT TB_TODO_PK PRIMARY KEY,
	TITLE VARCHAR2(300BYTE),
	DETAIL VARCHAR2(1000BYTE),
	COMPLETE NUMBER(1),
	REG_DATE DATE DEFAULT CURRENT_DATE,
	
	CONSTRAINT CK_BOOLEAN_COMPLETE CHECK (COMPLETE IN (0,1))
);

CREATE SEQUENCE SEQ_TODO_NO NOCACHE;

INSERT INTO TB_TODO VALUES(SEQ_TODO_NO.NEXTVAL, 'TodoList 복습', 'TodoList JDBC로 만들기', 0, DEFAULT); 

COMMIT;

SELECT * FROM TB_TODO;

DROP TABLE TB_TODO;
DROP SEQUENCE SEQ_TODO_NO;

UPDATE TB_TODO
		SET
			COMPLETE = DECODE( COMPLETE, 0, 1, 1, 0)
		WHERE TODO_NO = 2;