CREATE TABLE TB_TODO(
	TODO_NO NUMBER CONSTRAINT TB_TODO_PK PRIMARY KEY,
	TODO_TITLE VARCHAR2(300BYTE),
	TODO_DETAIL VARCHAR2(1000BYTE),
	TODO_COMPLETE NUMBER(1) DEFAULT 0,
	REG_DATE DATE DEFAULT CURRENT_DATE,
	
	CONSTRAINT CK_BOOLEAN_COMPLETE CHECK (TODO_COMPLETE IN (0,1))
);

CREATE SEQUENCE SEQ_TODO_NO NOCACHE;

INSERT INTO TB_TODO VALUES(SEQ_TODO_NO.NEXTVAL, 'TodoList 복습', 'TodoList JDBC로 만들기', DEFAULT, DEFAULT); 

COMMIT;

SELECT * FROM TB_TODO
ORDER BY TODO_NO;

DROP TABLE TB_TODO;
DROP SEQUENCE SEQ_TODO_NO;

UPDATE TB_TODO
		SET
			TODO_COMPLETE = DECODE(TODO_COMPLETE, 0, 1, 1, 0)
		WHERE TODO_NO = 9;
		
DELETE
FROM TB_TODO
WHERE TODO_NO = 10;